apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "samba.fullname" . }}
  namespace: {{ include "samba.name" . }}
  labels:
    {{- include "samba.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "samba.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "samba.name" . }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: {{ include "samba.name" . }}-data
          persistentVolumeClaim:
            claimName: {{ include "samba.name" . }}-pvc
            readOnly: false
        - name: {{ include "samba.name" . }}-config
          configMap:
            name: timemachine-smb-config
        - name: avahi-services
          configMap:
            name: timemachine-avahi
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.samba.repository }}:{{ .Values.image.samba.tag }}"
          imagePullPolicy: {{ .Values.image.samba.pullPolicy }}
          ports:
            - name: smb
              containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: {{ include "samba.name" . }}-data
              mountPath: {{ .Values.volumes.samba.storage.mountPath }}
            - name: {{ include "samba.name" . }}-config
              mountPath: {{ .Values.volumes.samba.config.mountPath }}
              subPath: {{ .Values.volumes.samba.config.subPath }}
          env:
            - name: NAME
              value: {{ .Values.envVars.samba.timemachine.NAME }}
            - name: USER
              value: {{ .Values.envVars.samba.timemachine.USER }}
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: timemachine-credentials
                  key: PASS
            - name: UID
              value: "1000"

            - name: GID
              value: "1000"

        - name: avahi
          image: "{{ .Values.image.avahi.repository }}:{{ .Values.image.avahi.tag }}"
          imagePullPolicy: {{ .Values.image.avahi.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache avahi dbus
              mkdir -p /run/dbus
              dbus-daemon --system --fork
              exec avahi-daemon --no-chroot --debug
#          volumeMounts:
#            - name: avahi-data
#              mountPath: {{ .Values.volumes.avahi.mountPath }}
